unbind C-b
set -g prefix F12
bind-key F12 send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status-style "bg=default"
set -g status-right-length 120
set -g status-left ""
set -g status-right '#[fg=#9ccfd8]#(cd #{q:pane_current_path} && git rev-parse --abbrev-ref HEAD) #[fg=#6e6a86]%H:%M '
set -g status-interval 5

setw -g window-status-format "#[fg=#6e6a86] #I"
setw -g window-status-current-format "#[fg=#9ccfd8] #I"
setw -g window-status-separator ""

bind g popup -B -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"
bind f popup -B -w 60% -h 30% -E 'bash "$HOME/.config/tmux/sessionizer.sh" #{q:client_name}'
bind w popup -B -w 90% -h 90% -EE 'bash "$HOME/.config/tmux/wallpaper.sh" #{q:client_name}'
