set -g prefix F12
unbind C-b

set -g mouse on
set -g focus-events on
set -g escape-time 0
set -g base-index 1
set -g renumber-windows on

set -g status-position bottom
set -g status-style "bg=#090B10"
set -g status-left-length 0
set -g status-right-length 200
set -g status-left ""
set -g status-right "#[fg=#908caa]#(echo #{pane_current_path} | sed \"s|^$HOME|~|\") "

setw -g window-status-format "#[fg=#6e6a86] #I"
setw -g window-status-current-format "#[fg=#e0def4,bold] #I"
setw -g window-status-separator ""

bind c new-window -c "#{pane_current_path}"
bind s popup -w 100% -h 40% -x C -y 9999 -E "$HOME/.config/tmux/tmux-sessionizer.sh"
bind w popup -w 100% -h 40% -x C -y 9999 -E "$HOME/.config/tmux/tmux-worktree.sh"

