set -g prefix F12
unbind C-b

set -g mouse on
set -g focus-events on
set -g escape-time 0
set -g base-index 1
set -g renumber-windows on

bind c new-window -c "#{pane_current_path}"
bind s popup -w 100% -h 40% -x C -y 9999 -E "$HOME/.config/tmux/tmux-sessionizer.sh"
bind w popup -w 100% -h 40% -x C -y 9999 -E "$HOME/.config/tmux/tmux-worktree.sh"

