# vim:fileencoding=utf-8:foldmethod=marker
font_size 16
disable_ligatures always
cursor_shape block
cursor_blink_interval 0
cursor_trail 3
cursor_trail_start_threshold 20
cursor_trail_decay 0.1 0.4

background #090B10
hide_window_decorations titlebar-only
window_padding_width 0

mouse_hide_wait 0
confirm_os_window_close 0
shell_integration no-title no-cursor
allow_remote_control yes

copy_on_select clipboard

map_timeout 1.0

tab_bar_style none
tab_bar_edge hidden

include current-theme.conf



# BEGIN_KITTY_FONTS
font_family      family="FantasqueSansM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
