# vim:fileencoding=utf-8:foldmethod=marker
font_size 16
disable_ligatures always
cursor_shape block
cursor_blink_interval 0
cursor_trail 3
cursor_trail_start_threshold 20
cursor_trail_decay 0.1 0.4

background #090B10
hide_window_decorations titlebar-only
window_padding_width 0

mouse_hide_wait 0
confirm_os_window_close 0
shell_integration no-title no-cursor
allow_remote_control yes

copy_on_select clipboard

map_timeout 1.0

tab_bar_edge bottom 
tab_bar_min_tabs 1
tab_bar_style custom
tab_separator " "
tab_bar_filter session:~
tab_title_template "{index}"
active_tab_title_template "{index}"

include current-theme.conf

tab_bar_background #090B10
active_tab_background #090B10
inactive_tab_background #090B10
active_tab_foreground #e0def4
inactive_tab_foreground #908caa
active_tab_font_style bold
inactive_tab_font_style normal



# BEGIN_KITTY_FONTS
font_family      family="FantasqueSansM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
