"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[palette]
base = "#191724"
surface = "#1f1d2e"
text = "#e0def4"
subtle = "#908caa"
love = "#eb6f92"
foam = "#9ccfd8"
iris = "#c4a7e7"
gold = "#f6c177"

[[blocks]]
type = "prompt"
alignment = "left"
segments = [
  { type = "path", style = "plain", foreground = "p:iris", template = "{{ .Path }}", options = { style = "full", mapped_locations = { "~" = "~" } } },
  { type = "git", style = "plain", foreground = "p:foam", template = " {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if gt .StashCount 0 }} <#f6c177>*{{ .StashCount }}</>{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }} ", options = { fetch_status = true, fetch_push_status = true, branch_icon = " ", status_formats = { Added = "<#9ccfd8>+%d</> ", Deleted = "<#eb6f92>-%d</> ", Modified = "<#c4a7e7>~%d</> ", Untracked = "<#31748f>?%d</> ", Unmerged = "<#eb6f92>x%d</> " } } }
]

[[blocks]]
type = "prompt"
alignment = "left"
newline = true
segments = [
  { type = "text", style = "plain", foreground = "p:love", template = "❯" }
]
